repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
        exclude_types:
          - csv
          - svg
    -   id: trailing-whitespace
    - id: name-tests-test
      args: [ "--django" ]
-   repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
    -   id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
-   repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
    -   id: isort
        name: isort (python)
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    -   id: mypy
-   repo: https://github.com/pycqa/pylint
    rev: v2.11.1
    hooks:
    - id: pylint
      exclude: "[a-zA-Z]*/(migrations)/(.)*"
      args: [ "--load-plugins=pylint_django", "--django-settings-module=photofriends.settings" ]
      additional_dependencies: [
          pylint_django
      ]
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
    -   id: bandit
        exclude: /tests/
-   repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: poetry run pytest
        language: system
        pass_filenames: false
        always_run: true
