# Generated by Django 3.2.8 on 2021-10-31 22:57

import uuid

from django.db import migrations, models
import django.db.models.deletion

import app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Album name", max_length=64, verbose_name="Album name"
                    ),
                ),
                (
                    "creator",
                    models.CharField(
                        help_text="Your name", max_length=64, verbose_name="Creator"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=app.models.get_utc_now,
                        help_text="Date in format ISO8601. Example: 2020-03-03T18:31:01.915000Z.",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(default=True, verbose_name="Album enabled"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Upload",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        help_text="Select one or more images to upload",
                        upload_to="photos",
                        verbose_name="Image to upload",
                    ),
                ),
                ("thumbnail", models.ImageField(editable=False, upload_to="thumbs")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=app.models.get_utc_now,
                        help_text="Date in format ISO8601. Example: 2020-03-03T18:31:01.915000Z.",
                    ),
                ),
                ("uploader", models.CharField(max_length=64, verbose_name="Name")),
                (
                    "album",
                    models.ForeignKey(
                        help_text="Related Album",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app.album",
                    ),
                ),
            ],
        ),
    ]
